version: '3'

services:
  mariadb:
#    image: mariadb:latest
    image: mariadb:inception
    build: requirements/mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --host=localhost --user=root --password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB_NAME=wp_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - database_network
      - nginx_network

  wordpress:
#    image: wordpress:latest
    image: wordpress:inception
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "php", "--run", "echo 'PHP is working';"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB_NAME=wp_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
      - WP_PATH=/var/www/html
      - WP_DB_HOST=mariadb:3306
      - WP_DB_NAME=wp_db
      - WP_DB_USER=db_user
      - WP_DB_PASSWORD=db_pass
      - WP_URL=takira.42.fr
      - WP_TITLE=wp_title
      - WP_ADMIN_USER=wp_admin
      - WP_ADMIN_PASSWORD=wp_admin_pass
      - WP_ADMIN_EMAIL=ad_admin@email.com
      - WP_EDITOR_USER=wp_editor_user
      - WP_EDITOR_PASSWORD=wp_editor_pass
      - WP_EDITOR_EMAIL=ep_editor@email.com
    volumes:
      - wp_data:/var/www/html
    networks:
      - nginx_network

  nginx:
#    image: nginx:latest
    image: nginx:inception
    build: requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
      hugo:
        condition: service_healthy
    ports:
      - "443:443"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure https://192.168.1.10 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - wp_data:/var/www/html
    networks:
      nginx_network:
        ipv4_address: 192.168.1.10  # takira.42.fr or takira.hugo.com
    dns:
      - 192.168.1.53

  dnsmasq:
    image: dnsmasq:inception
    build: requirements/bonus/dnsmasq
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "10.0.2.15:53:53/udp"  # todo: env
      - "10.0.2.15:53:53/tcp"  # todo: env
    cap_add:
      - NET_ADMIN
    restart: always
    healthcheck:
      test: ["CMD", "nslookup", "takira.42.fr", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      nginx_network:
        ipv4_address: 192.168.1.53

  adminer:
    image: adminer:inception
    build: requirements/bonus/adminer
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - database_network

  redis:
    image: redis:inception
    build: requirements/bonus/redis
    ports:
      - "10.0.2.15:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - nginx_network
#
#  ftp:
#    networks:
#      - nginx_network

  hugo:
    image: hugo:inception
    build: requirements/bonus/hugo
    ports:
      - "1313:1313"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:1313 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - /var/www/blog:/var/www/blog
    networks:
      - nginx_network

volumes:
  db_data:
  wp_data:

networks:
  nginx_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24  # 192.168.1.1~192.168.1.254
  database_network:
