version: '3'

services:
  mariadb:
#    image: mariadb:latest # tmp
    build: requirements/mariadb
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASS" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASS
      - MYSQL_DB_NAME
      - MYSQL_USER
      - MYSQL_PASS
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
#    build: requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:80/wp-admin/install.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - WP_DB_HOST
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_PASS
    volumes:
      - wp_data:/var/www/html
    networks:
      - wordpress_network

  nginx:
#    image: nginx:latest
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --insecure https://localhost:443 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - wp_data:/var/www/html
    networks:
      - wordpress_network

  adminer:
    build: requirements/bonus/adminer
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wordpress_network


volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:
