version: '3'

services:
  mariadb:
#    image: mariadb:latest # tmp
    build: requirements/mariadb
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
#    image: wordpress:latest
    build: requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes:
      - wp_data:/var/www/html
    networks:
      - wordpress_network

#  nginx:
#    build: requirements/nginx
#    depends_on:
#      - wordpress
#    ports:
#      - "443:443"
#    restart: always
#    volumes:
#      - wp_data:/var/www/html
#    networks:
#      - wordpress_network

#  adminer:
#    build: requirements/bonus/adminer
#    depends_on:
#      - mariadb
#      - wordpress
#    ports:
#      - "8080:8080"
#    restart: always
#    networks:
#      - wordpress_network


volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:

# https://qiita.com/nakazawaken1/items/09d6cbef3dae6dbaf765
#version: "3.7"
#services:
#  db:
#    image: mariadb:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: wordpress_db
#      MYSQL_USER: wordpress_user
#      MYSQL_PASSWORD: wordpress_pass
#  ap:
#    image: wordpress:latest
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8000:80"
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: wordpress_user
#      WORDPRESS_DB_PASSWORD: wordpress_pass
#      WORDPRESS_DB_NAME: wordpress_db
