version: '3.4'

# services ---------------------------------------------------------------------
services:
  mariadb:
    image: mariadb:inception
    build: requirements/mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --host=localhost --user=root --password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is not set}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME:?MYSQL_DB_NAME is not set}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is not set}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set}
      DB_CONTAINER_PATH: ${DB_CONTAINER_PATH:?DB_CONTAINER_PATH is not set}
    volumes:
      - db_data:${DB_CONTAINER_PATH:?DB_CONTAINER_PATH is not set}
      - /var/log/inception/mysql:/var/log/mysql
    networks:
      - database_network

  wordpress:
    image: wordpress:inception
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      dnsmasq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "php --run \"echo 'PHP is working';\" && redis-cli -h redis ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is not set}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME:?MYSQL_DB_NAME is not set}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is not set}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set}
      WP_CONTAINER_PATH: ${WP_CONTAINER_PATH:?WP_CONTAINER_PATH is not set}
      WP_DB_HOST: ${WP_DB_HOST:?WP_DB_HOST is not set}
      WP_DB_NAME: ${WP_DB_NAME:?WP_DB_NAME is not set}
      WP_DB_USER: ${WP_DB_USER:?WP_DB_USER is not set}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD:?WP_DB_PASSWORD is not set}
      WP_URL: ${WP_URL:?WP_URL is not set}
      WP_TITLE: ${WP_TITLE:?WP_TITLE is not set}
      WP_ADMIN_USER: ${WP_ADMIN_USER:?WP_ADMIN_USER is not set}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD:?WP_ADMIN_PASSWORD is not set}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL:?WP_ADMIN_EMAIL is not set}
      WP_EDITOR_USER: ${WP_EDITOR_USER:?WP_EDITOR_USER is not set}
      WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD:?WP_EDITOR_PASSWORD is not set}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL:?WP_EDITOR_EMAIL is not set}
    volumes:
      - wp_data:${WP_CONTAINER_PATH:?WP_CONTAINER_PATH is not set}
      - /var/log/inception/wordpress:/var/www/html/wp-content/logs
    networks:
      - database_network
      - web_network

  nginx:
    image: nginx:inception
    build: requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
      hugo:
        condition: service_healthy
      dnsmasq:
        condition: service_healthy
    ports:
      - "443:443"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure https://$WP_DOMAIN || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - wp_data:${WP_CONTAINER_PATH:?WP_CONTAINER_PATH is not set}
      - hugo_data:${HUGO_CONTAINER_PATH:?HUGO_CONTAINER_PATH is not set}
      - /var/log/inception/nginx:/var/log/nginx
    networks:
      web_network:
        ipv4_address: ${WEB_PAGE_IP:?WEB_PAGE_IP is not set}  # takira.42.fr or takira.hugo.com
    environment:
      COUNTRY: ${COUNTRY:?COUNTRY is not set}
      STATE: ${STATE:?STATE is not set}
      ORGANIZATION: ${ORGANIZATION:?ORGANIZATION is not set}
      CRT_DIR: ${CRT_DIR:?CRT_DIR is not set}
      RSA_KEY_BITS: ${RSA_KEY_BITS:?RSA_KEY_BITS is not set}
      WP_DOMAIN: ${WP_DOMAIN:?WP_DOMAIN is not set}
      HUGO_DOMAIN: ${HUGO_DOMAIN:?HUGO_DOMAIN is not set}
    dns:
      - ${DNSMASQ_IP:?DNSMASQ_IP is not set}

  redis:
    image: redis:inception
    build: requirements/bonus/redis
    ports:
      - "${HOST_IP}:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - web_network

  dnsmasq:
    image: dnsmasq:inception
    build: requirements/bonus/dnsmasq
    ports:
      - "${HOST_IP}:53:53/udp"
      - "${HOST_IP}:53:53/tcp"
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/log/inception/dnsmasq:/var/log/dnsmasq
    restart: always
    healthcheck:
      test: ["CMD", "nslookup", "takira.42.fr", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      web_network:
        ipv4_address: ${DNSMASQ_IP:?DNSMASQ_IP is not set}

  adminer:
    image: adminer:inception
    build: requirements/bonus/adminer
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - database_network

  ftpd:
    image: ftpd:inception
    build: requirements/bonus/ftpd
    ports:
      - "21:21"
      - "30000:30000"
    volumes:
      - wp_data:${WP_CONTAINER_PATH:?WP_CONTAINER_PATH is not set}
      - /var/log/inception/pure-ftpd:/var/log/pure-ftpd
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "echo -e 'QUIT\r\n' | nc localhost 21 | grep '220'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      WP_CONTAINER_PATH: ${WP_CONTAINER_PATH:?WP_CONTAINER_PATH is not set}
      PUBLIC_HOST: ${PUBLIC_HOST:?PUBLIC_HOST is not set}
      FTP_USER: ${FTP_USER:?FTP_USER is not set}
      FTP_PASSWORD: ${FTP_PASSWORD:?FTP_PASSWORD is not set}

  hugo:
    image: hugo:inception
    build: requirements/bonus/hugo
    ports:
      - "1313:1313"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:1313 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - hugo_data:${HUGO_CONTAINER_PATH:?HUGO_CONTAINER_PATH is not set}
    networks:
      - web_network
    environment:
      HUGO_CONTAINER_PATH: ${HUGO_CONTAINER_PATH:?HUGO_CONTAINER_PATH is not set}

# volumes ----------------------------------------------------------------------
volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      device: ${DB_VOLUME_DIR:?DB_VOLUME_DIR is not set}
      type: anything_is_ok
  wp_data:
    driver: local
    driver_opts:
      o: bind
      device: ${WP_VOLUME_DIR:?WP_VOLUME_DIR is not set}
      type: anything_is_ok
  hugo_data:
    driver: local
    driver_opts:
      o: bind
      device: ${HUGO_VOLUME_DIR:?HUGO_VOLUME_DIR is not set}
      type: anything_is_ok


# networks ---------------------------------------------------------------------
networks:
  web_network:
    ipam:
      config:
        - subnet: ${NGINX_NETWORK_SUBNET:?NGINX_NETWORK_SUBNET is not set}
  database_network:
